import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { Card, Title, Paragraph, Button } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';

const InvoiceViewerScreen = ({ navigation, route }) => {
  const { requestId } = route.params;
  const [loading, setLoading] = useState(true);
  const [invoiceData, setInvoiceData] = useState(null);

  useEffect(() => {
    // In a real app, you would fetch invoice data here
    // For now, we'll simulate the data
    setTimeout(() => {
      setInvoiceData({
        id: requestId,
        cultivator: 'John Doe',
        plantType: 'Mangrove',
        co2Removed: 2.5,
        credits: 2.5,
        txHash: '0x1234567890abcdef...',
        date: new Date().toLocaleDateString(),
      });
      setLoading(false);
    }, 1000);
  }, [requestId]);

  const downloadInvoice = () => {
    Alert.alert('Download', 'Invoice downloaded successfully!');
  };

  const shareInvoice = () => {
    Alert.alert('Share', 'Invoice shared successfully!');
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#22c55e" />
        <Text style={styles.loadingText}>Loading invoice...</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <MaterialCommunityIcons name="file-document" size={40} color="#22c55e" />
        <Title style={styles.title}>Carbon Credit Invoice</Title>
        <Paragraph style={styles.subtitle}>
          Verified by National Carbon Credit Registry
        </Paragraph>
      </View>

      <Card style={styles.invoiceCard}>
        <Card.Content>
          <View style={styles.invoiceHeader}>
            <Text style={styles.invoiceTitle}>CARBON CREDIT INVOICE</Text>
            <Text style={styles.invoiceId}>INV-{String(requestId).padStart(6, '0')}</Text>
          </View>

          <View style={styles.invoiceDetails}>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Date:</Text>
              <Text style={styles.detailValue}>{invoiceData.date}</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Transaction Hash:</Text>
              <Text style={styles.detailValue}>{invoiceData.txHash}</Text>
            </View>
          </View>

          <View style={styles.cultivatorSection}>
            <Text style={styles.sectionTitle}>Cultivator Information</Text>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Name:</Text>
              <Text style={styles.detailValue}>{invoiceData.cultivator}</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Plant Type:</Text>
              <Text style={styles.detailValue}>{invoiceData.plantType}</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>CO2 Removed:</Text>
              <Text style={styles.detailValue}>{invoiceData.co2Removed} tons</Text>
            </View>
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Credits Issued:</Text>
              <Text style={styles.detailValue}>{invoiceData.credits} credits</Text>
            </View>
          </View>

          <View style={styles.verificationSection}>
            <Text style={styles.sectionTitle}>Verification</Text>
            <Text style={styles.verificationText}>
              This carbon credit has been verified by the National Carbon Credit Registry (NCCR).
              The plantation of {invoiceData.plantType} has been confirmed to remove {invoiceData.co2Removed} tons 
              of CO2 from the atmosphere, earning the cultivator {invoiceData.credits} carbon credits.
            </Text>
            <Text style={styles.verificationText}>
              This credit is backed by blockchain technology and is immutable.
            </Text>
          </View>

          <View style={styles.signatureSection}>
            <Text style={styles.sectionTitle}>Digital Signature</Text>
            <Text style={styles.signatureText}>
              Verified by: NCCR Admin{'\n'}
              Date: {invoiceData.date}{'\n'}
              Digital Signature: {invoiceData.txHash.slice(0, 16)}...
            </Text>
          </View>

          <View style={styles.footer}>
            <Text style={styles.footerText}>
              This is an automated invoice generated by the CarbonChain system.
              For support, contact: support@carbonchain.com
            </Text>
          </View>
        </Card.Content>
      </Card>

      <View style={styles.actionButtons}>
        <Button
          mode="contained"
          onPress={downloadInvoice}
          style={styles.actionButton}
          buttonColor="#22c55e"
          icon={() => <MaterialCommunityIcons name="download" size={20} color="#fff" />}
        >
          Download PDF
        </Button>
        <Button
          mode="outlined"
          onPress={shareInvoice}
          style={styles.actionButton}
          icon={() => <MaterialCommunityIcons name="share" size={20} color="#22c55e" />}
        >
          Share
        </Button>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0fdf4',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#6b7280',
  },
  header: {
    padding: 20,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#22c55e',
    marginTop: 10,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
  },
  invoiceCard: {
    margin: 20,
    elevation: 4,
    borderRadius: 12,
  },
  invoiceHeader: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#22c55e',
  },
  invoiceTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#22c55e',
    marginBottom: 5,
  },
  invoiceId: {
    fontSize: 14,
    color: '#6b7280',
  },
  invoiceDetails: {
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  detailValue: {
    fontSize: 14,
    color: '#6b7280',
    flex: 1,
    textAlign: 'right',
  },
  cultivatorSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: 10,
  },
  verificationSection: {
    marginBottom: 20,
  },
  verificationText: {
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 20,
    marginBottom: 10,
  },
  signatureSection: {
    marginBottom: 20,
  },
  signatureText: {
    fontSize: 14,
    color: '#6b7280',
    fontFamily: 'monospace',
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: '#d1d5db',
    paddingTop: 15,
  },
  footerText: {
    fontSize: 12,
    color: '#6b7280',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
    padding: 20,
    gap: 10,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 8,
  },
});

export default InvoiceViewerScreen;
