import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from config import Config

def generate_invoice(request_id, user_name, plant_type, co2_removed, credits, tx_hash, invoice_folder):
    """
    Generate PDF invoice using ReportLab
    """
    # Ensure invoice folder exists
    os.makedirs(invoice_folder, exist_ok=True)
    
    # Create invoice filename
    invoice_filename = f"invoice_{request_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    invoice_path = os.path.join(invoice_folder, invoice_filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(invoice_path, pagesize=letter)
    story = []
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.darkgreen
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.darkblue
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=6
    )
    
    # Title
    story.append(Paragraph("CARBON CREDIT INVOICE", title_style))
    story.append(Spacer(1, 20))
    
    # Invoice details
    story.append(Paragraph("Invoice Details", header_style))
    
    invoice_data = [
        ['Invoice ID:', f'INV-{request_id:06d}'],
        ['Date:', datetime.now().strftime('%B %d, %Y')],
        ['Time:', datetime.now().strftime('%H:%M:%S')],
        ['Transaction Hash:', tx_hash],
        ['', '']
    ]
    
    invoice_table = Table(invoice_data, colWidths=[2*inch, 4*inch])
    invoice_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    story.append(invoice_table)
    story.append(Spacer(1, 20))
    
    # Cultivator information
    story.append(Paragraph("Cultivator Information", header_style))
    cultivator_data = [
        ['Name:', user_name],
        ['Plant Type:', plant_type],
        ['CO2 Removed:', f'{co2_removed} tons'],
        ['Credits Issued:', f'{credits} credits'],
    ]
    
    cultivator_table = Table(cultivator_data, colWidths=[2*inch, 4*inch])
    cultivator_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    story.append(cultivator_table)
    story.append(Spacer(1, 20))
    
    # Verification section
    story.append(Paragraph("Verification", header_style))
    verification_text = f"""
    This carbon credit has been verified by the National Carbon Credit Registry (NCCR).
    
    The plantation of {plant_type} has been confirmed to remove {co2_removed} tons of CO2 
    from the atmosphere, earning the cultivator {credits} carbon credits.
    
    This credit is backed by blockchain technology and is immutable.
    """
    
    story.append(Paragraph(verification_text, normal_style))
    story.append(Spacer(1, 20))
    
    # Signature section
    story.append(Paragraph("Digital Signature", header_style))
    signature_text = """
    Verified by: NCCR Admin
    Date: """ + datetime.now().strftime('%B %d, %Y') + """
    Digital Signature: """ + tx_hash[:16] + "..."
    
    story.append(Paragraph(signature_text, normal_style))
    story.append(Spacer(1, 30))
    
    # Footer
    footer_text = """
    <i>This is an automated invoice generated by the DeCarbon system by QuantumNodes.
    For support, contact: support@decarbon.com</i>
    """
    
    story.append(Paragraph(footer_text, normal_style))
    
    # Build PDF
    doc.build(story)
    
    return invoice_path

def generate_purchase_invoice(transaction_id, buyer_name, seller_name, credits, amount, tx_hash, invoice_folder):
    """
    Generate PDF invoice for credit purchase transactions
    """
    # Ensure invoice folder exists
    os.makedirs(invoice_folder, exist_ok=True)
    
    # Create invoice filename
    invoice_filename = f"purchase_invoice_{transaction_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    invoice_path = os.path.join(invoice_folder, invoice_filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(invoice_path, pagesize=letter)
    story = []
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.darkgreen
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.darkblue
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=6
    )
    
    # Title
    story.append(Paragraph("CARBON CREDIT PURCHASE INVOICE", title_style))
    story.append(Spacer(1, 20))
    
    # Invoice details
    story.append(Paragraph("Invoice Details", header_style))
    
    invoice_data = [
        ['Invoice ID:', f'PUR-{transaction_id:06d}'],
        ['Date:', datetime.now().strftime('%B %d, %Y')],
        ['Time:', datetime.now().strftime('%H:%M:%S')],
        ['Transaction Hash:', tx_hash],
        ['', '']
    ]
    
    invoice_table = Table(invoice_data, colWidths=[2*inch, 4*inch])
    invoice_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    story.append(invoice_table)
    story.append(Spacer(1, 20))
    
    # Purchase information
    story.append(Paragraph("Purchase Information", header_style))
    purchase_data = [
        ['Buyer:', buyer_name],
        ['Seller:', seller_name],
        ['Credits Purchased:', f'{credits} credits'],
        ['Amount Paid:', f'₹{amount:.2f}'],
    ]
    
    purchase_table = Table(purchase_data, colWidths=[2*inch, 4*inch])
    purchase_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    story.append(purchase_table)
    story.append(Spacer(1, 20))
    
    # Verification section
    story.append(Paragraph("Verification", header_style))
    verification_text = f"""
    This carbon credit purchase has been verified and recorded on the blockchain.
    
    {buyer_name} has purchased {credits} carbon credits from {seller_name} for ₹{amount:.2f}.
    
    The transaction has been recorded with transaction hash: {tx_hash}
    
    This purchase is backed by blockchain technology and is immutable.
    """
    
    story.append(Paragraph(verification_text, normal_style))
    story.append(Spacer(1, 20))
    
    # Signature section
    story.append(Paragraph("Digital Signature", header_style))
    signature_text = """
    Verified by: DeCarbon System
    Date: """ + datetime.now().strftime('%B %d, %Y') + """
    Digital Signature: """ + tx_hash[:16] + "..."
    
    story.append(Paragraph(signature_text, normal_style))
    story.append(Spacer(1, 30))
    
    # Footer
    footer_text = """
    <i>This is an automated invoice generated by the DeCarbon system by QuantumNodes.
    For support, contact: support@decarbon.com</i>
    """
    
    story.append(Paragraph(footer_text, normal_style))
    
    # Build PDF
    doc.build(story)
    
    return invoice_path




